version: '3.3'

services:
    zoo1:
        image: zookeeper:3.4
        hostname: zoo1
        ports:
            - target: 2181
              published: 2181
              protocol: tcp
              mode: host
            - target: 2888
              published: 2888
              protocol: tcp
              mode: host
            - target: 3888
              published: 3888
              protocol: tcp
              mode: host
        networks:
            - zoonet
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /home/lutz/zookeeper/my-docker-entrypoint.sh:/docker-entrypoint.sh
            - /home/lutz/zookeeper:/conf
            - z1-data:/data
            - z1-datalog:/datalog
    zoo2:
        image: zookeeper:3.4
        hostname: zoo2
        ports:
            - target: 2181
              published: 2181
              protocol: tcp
              mode: host
            - target: 2888
              published: 2888
              protocol: tcp
              mode: host
            - target: 3888
              published: 3888
              protocol: tcp
              mode: host
        networks:
            - zoonet
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /home/lutz/zookeeper/my-docker-entrypoint.sh:/docker-entrypoint.sh
            - /home/lutz/zookeeper:/conf
            - z2-data:/data
            - z2-datalog:/datalog
    zoo3:
        image: zookeeper:3.4
        hostname: zoo3
        ports:
            - target: 2181
              published: 2181
              protocol: tcp
              mode: host
            - target: 2888
              published: 2888
              protocol: tcp
              mode: host
            - target: 3888
              published: 3888
              protocol: tcp
              mode: host
        networks:
            - zoonet
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
        volumes:
            - /home/lutz/zookeeper/my-docker-entrypoint.sh:/docker-entrypoint.sh
            - /home/lutz/zookeeper:/conf
            - z3-data:/data
            - z3-datalog:/datalog
networks:
    zoonet:

volumes:
    z1-data:
    z1-datalog:
    z2-data:
    z2-datalog:
    z3-data:
    z3-datalog:
